apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  selector:
    app: simple-app
    # app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      